sudo: false

language: node_js
node_js:
  - "8.16.0"
  - "10.16.0"

cache:
  directories:
    - node_modules

install:
  - npm install --no-optional --ignore-scripts

script:
  - npm run build
  - npm run lint
